services:
  mongodb:
    container_name: mongodb
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: jwtsecurity
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb: