services:
  mongodb:
    container_name: mongodb
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: jwtsecurity
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: backend-chef-ai
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_ATLAS_URI: mongodb://mongodb:27017/jwtsecurity
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mongodb: